### ISSUE TITLE
Plugins appearing dark on dark background even when currentColor is used

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-fs#127]
### Expected Behavior

All the images have `currentColor` used in them, and hence they should have appeared light on dar background.

### Actual Behaviour

Plugins are appearing dark on dark background.

<img width="1452" alt="Screenshot 2024-05-16 at 4 13 20 PM" src="https://github.com/kestra-io/plugin-fs/assets/6594483/7e36005b-8773-4494-9011-c3a4a00145f8">

### Steps To Reproduce

N/A

### Environment Information

- Kestra Version: N/A
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by brian-mulier-p** [comment]
Closing in favor of a docs' repo issue https://github.com/kestra-io/docs/issues/1356
