### ISSUE TITLE
Samba

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-fs#23]

**Comment by tchiotludo** [comment]
Branch started here : https://github.com/kestra-io/plugin-fs/blob/feat/samba/docker-compose-ci.yml

**Comment by brian-mulier-p** [comment]
https://github.com/kestra-io/plugin-fs/tree/feat/samba

**Comment by brian-mulier-p** [comment]
https://github.com/kestra-io/plugin-fs/tree/feat/samba
