### ISSUE TITLE
HTTP/Download: Allow empty response

### ISSUE THREAD

**Issue by PierreZ** [kestra-io/plugin-fs#63]
Hi :wave: 

I have a usecase where I'm downloading many files from an API that may returns legit, empty files. Using the latest version of the plugin, an error is thrown here:

https://github.com/kestra-io/plugin-fs/blob/2ed09eb70923a1c6734c583791be55f49609ad71/src/main/java/io/kestra/plugin/fs/http/Download.java#L95-L97

Would that be possible to:

* avoid failing conditionally based on an input property (default will keep the current behavior),
* report back the size in an output property so that we can handle the case if needed

I would be happy to make the contribution if needed :smile:

**Comment by loicmathieu** [comment]
Hi @PierreZ, happy to see you there ;)
We are always very happy to have contributors, so your contribution is highly welcomed.

I agree with you that this should not have been done like that but I don't know if we can change the default behaviour so having a `failOnEmptyResponse` boolean property for ex, that default to true is a nice workaround.
You can also add the size in the output it's a nice addition.

By the way, do you join our Slack, we will love to have some feedback from you on Kestra ;)

**Comment by PierreZ** [comment]
I will join the Slack, and make the PR then 😎

**Comment by PierreZ** [comment]
I wrote the patch, seems like the [url used in the test](https://github.com/kestra-io/plugin-fs/blob/2ed09eb70923a1c6734c583791be55f49609ad71/src/test/java/io/kestra/plugin/fs/http/DownloadTest.java#L63) `https://run.mocky.io/v3/bd4e25ed-2de1-44c9-b613-9612c965684b` is always responding 503.

Should I be modifying the URL :thinking:?

**Comment by loicmathieu** [comment]
@PierreZ yes, if you can find a different URL for the test this would be great.
We should use Wiremock instead to have embedded test, we can do it another time as long as the test pass it'll be OK for me ;) 

> EDIT: should I also add some checks about the HTTP responde code? Feels like the empty body is a workaround around bad HTTP response

I was surprised to see this empty body stuff, we should have relied on HTTP code instead and I'm not sure whether or not an error code will generate an exception, this should be check before we do anything about this.

**Comment by loicmathieu** [comment]
@PierreZ we will soon move the HTTP tasks into their own repo (in fact copy and let these one there for backward compatibility) so if you can push your PR this would be great so we can integrate it in the new repos.

**Comment by PierreZ** [comment]
Right, I will try to push the PR today ;)
