### ISSUE TITLE
Ability to use shared directories (network, Windows share, Samba protocol, etc.)

### ISSUE THREAD

**Issue by AnthonyProData** [kestra-io/plugin-fs#78]
### Feature description

In various projects, third parties may generate files for various reasons. Today, this processing is carried out by dropping files onto shared directories (using various protocols, including Windows sharing, Samba, etc.). It would be interesting to have a feature that would allow us to launch Kestra as soon as we receive a file in this directory, but also to be able to retrieve the file in order to process it.

I hope I've gone into enough detail here.

**Comment by AnthonyProData** [comment]
Thank you for your responsiveness. 

I've just checked with my customer and it's true that the Samba protocol is used. Sorry, but I have one more question. 

Will the share folder be accessible from Kestra, which is running on a Docker? If I'm not mistaken, the folder must be mapped in the Yaml docker-compose file when the container is installed so that it can be accessed from inside a container. Once mapped, do I have to modify my docker-compose? If necessary, I can create a recipe for this update.

**Comment by tchiotludo** [comment]
it's the first it's will be more like our [sftp](https://kestra.io/plugins/plugin-fs#sftp) plugins, that will download all files remotely in a Kestra tasks, so no need to mount anything, it will be accessible over the network

**Comment by AnthonyProData** [comment]
Ah, I can't wait to test this functionality!

**Comment by anna-geller** [comment]
hey, sorry for the delayed response but we now support Samba protocol https://kestra.io/plugins/plugin-fs#smb

please check and reopen if this doesn't address your issue 👍
